# Generated by Django 3.0.5 on 2020-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200610_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='direction_phone',
            field=models.PositiveIntegerField(choices=[(48, 'Polska +48'), (1, 'USA +1'), (39, 'Włochy +39')], null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
