# Generated by Django 3.0.5 on 2020-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200612_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
