# Generated by Django 3.0.5 on 2020-06-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
