# Generated by Django 3.0.5 on 2020-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[(36, 'S'), (38, 'M'), (40, 'L'), (42, 'XL')], default='S', max_length=20),
        ),
    ]
