# Generated by Django 3.0.5 on 2020-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_auto_20200623_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_products',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
