# Generated by Django 3.0.5 on 2020-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
