# Generated by Django 3.0.5 on 2020-06-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_self_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='self_phone',
            new_name='phone',
        ),
    ]
