# Generated by Django 3.0.5 on 2020-06-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_pictrue'),
        ('orders', '0009_commentsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myshop.Product'),
            preserve_default=False,
        ),
    ]
