# Generated by Django 3.0.5 on 2020-06-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_commentsitem_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsitem',
            name='product',
        ),
        migrations.AddField(
            model_name='commentsitem',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem'),
            preserve_default=False,
        ),
    ]
