# Generated by Django 3.0.5 on 2020-06-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200617_0854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsItem',
        ),
    ]
